#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    h = s[:2]
    m = s[3:5]
    sec = s[6:8]
    e = s[8:]
    # return h+":"+m+":"+sec
    if h=="12":
        if e=="AM":
            h = "00"
    else:
        if e=="PM":
            h = str(int(h)+12)
    return h+":"+m+":"+sec
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
